// src/app/components/VideoBackground.tsx
import { useState, useEffect } from 'react';
import { getBackgroundImages } from '../../api';
import { isVideo } from '../../utils/mediaUtils';

interface VideoBackgroundProps {
  forcedUrl: string | null;
}

export function VideoBackground({ forcedUrl }: VideoBackgroundProps) {
  const [currentUrl, setCurrentUrl] = useState<string | null>(null);

  useEffect(() => {
    if (forcedUrl) {
      setCurrentUrl(forcedUrl);
    }
  }, [forcedUrl]);

  return (
    <div className="fixed inset-0 w-full h-full -z-10 bg-slate-900">
      {currentUrl ? (
        isVideo(currentUrl) ? (
          <video
            key={currentUrl} // Force reload on URL change
            autoPlay
            muted
            loop
            playsInline
            className="absolute inset-0 w-full h-full object-cover opacity-60 transition-opacity duration-1000"
          >
            <source src={currentUrl} type="video/mp4" />
          </video>
        ) : (
          <div
            className="absolute inset-0 bg-cover bg-center transition-opacity duration-1000"
            style={{ backgroundImage: `url(${currentUrl})` }}
          />
        )
      ) : (
        <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 animate-gradient" />
      )}

      {/* Overlay for better text readability */}
      <div className="absolute inset-0 bg-black/50" />

      {/* Optional: Animated particles effect */}
      <div className="absolute inset-0 opacity-20 pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-purple-500 rounded-full mix-blend-multiply filter blur-3xl animate-blob" />
        <div className="absolute top-1/3 right-1/4 w-64 h-64 bg-pink-500 rounded-full mix-blend-multiply filter blur-3xl animate-blob animation-delay-2000" />
        <div className="absolute bottom-1/4 left-1/3 w-64 h-64 bg-blue-500 rounded-full mix-blend-multiply filter blur-3xl animate-blob animation-delay-4000" />
      </div>
    </div>
  );
}

// src/app/components/video-background/video-background.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { trigger, style, animate, transition } from '@angular/animations';

@Component({
    selector: 'app-video-background',
    standalone: true,
    imports: [CommonModule],
    template: `
    <div class="fixed inset-0 w-full h-full overflow-hidden" style="z-index: 0;">
      @if (currentUrl) {
        @if (isVideo(currentUrl)) {
          <video
            [@fadeAnimation]
            [src]="currentUrl"
            class="absolute inset-0 w-full h-full object-cover"
            autoplay
            loop
            muted
            playsinline
          ></video>
        } @else {
          <img
            [@fadeAnimation]
            [src]="currentUrl"
            class="absolute inset-0 w-full h-full object-cover"
            alt="Background"
          />
        }
      }
      <!-- Overlay for better text readability -->
      <div class="absolute inset-0 bg-black/30"></div>
    </div>
  `,
    animations: [
        trigger('fadeAnimation', [
            transition(':enter', [
                style({ opacity: 0 }),
                animate('800ms ease-in', style({ opacity: 1 }))
            ]),
            transition(':leave', [
                animate('800ms ease-out', style({ opacity: 0 }))
            ])
        ])
    ]
})
export class VideoBackgroundComponent implements OnChanges {
    @Input() forcedUrl: string | null = null;
    currentUrl: string | null = null;

    ngOnChanges(changes: SimpleChanges): void {
        if (changes['forcedUrl'] && changes['forcedUrl'].currentValue) {
            this.currentUrl = changes['forcedUrl'].currentValue;
        }
    }

    isVideo(url: string): boolean {
        return url.includes('.mp4') || url.includes('.webm') || url.includes('video');
    }
}
