// src/app/components/media-modal/media-modal.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subject, takeUntil } from 'rxjs';
import { trigger, style, animate, transition } from '@angular/animations';
import { MediaService } from '../../services/media.service';
import { MediaItem } from '../../models/api.models';

@Component({
    selector: 'app-media-modal',
    standalone: true,
    imports: [CommonModule],
    template: `
    @if (isOpen && currentMedia) {
      <div 
        [@fadeAnimation]
        class="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4"
        (click)="close()"
      >
        <!-- Close button -->
        <button
          class="absolute top-4 right-4 z-10 p-2 rounded-full bg-white/10 hover:bg-white/20 transition-colors text-white"
          (click)="close()"
          aria-label="Close"
        >
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <!-- Media content -->
        <div 
          class="relative max-w-7xl max-h-[90vh] w-full"
          (click)="$event.stopPropagation()"
          [@scaleAnimation]
        >
          @if (currentMedia.type === 'image') {
            <img 
              [src]="currentMedia.url" 
              class="w-full h-full object-contain rounded-lg"
              alt="Full size media"
            />
          } @else if (currentMedia.type === 'video') {
            <video 
              [src]="currentMedia.url"
              class="w-full h-full object-contain rounded-lg"
              controls
              autoplay
            ></video>
          }
        </div>
      </div>
    }
  `,
    styles: [`
    :host {
      display: contents;
    }
  `],
    animations: [
        trigger('fadeAnimation', [
            transition(':enter', [
                style({ opacity: 0 }),
                animate('200ms', style({ opacity: 1 }))
            ]),
            transition(':leave', [
                animate('200ms', style({ opacity: 0 }))
            ])
        ]),
        trigger('scaleAnimation', [
            transition(':enter', [
                style({ transform: 'scale(0.9)', opacity: 0 }),
                animate('300ms cubic-bezier(0.4, 0, 0.2, 1)', style({ transform: 'scale(1)', opacity: 1 }))
            ]),
            transition(':leave', [
                animate('200ms', style({ transform: 'scale(0.9)', opacity: 0 }))
            ])
        ])
    ]
})
export class MediaModalComponent implements OnInit, OnDestroy {
    isOpen = false;
    currentMedia: MediaItem | null = null;
    private destroy$ = new Subject<void>();

    constructor(private mediaService: MediaService) { }

    ngOnInit(): void {
        this.mediaService.isOpen$
            .pipe(takeUntil(this.destroy$))
            .subscribe(isOpen => this.isOpen = isOpen);

        this.mediaService.currentMedia$
            .pipe(takeUntil(this.destroy$))
            .subscribe(media => this.currentMedia = media);
    }

    ngOnDestroy(): void {
        this.destroy$.next();
        this.destroy$.complete();
    }

    close(): void {
        this.mediaService.closeMedia();
    }
}

// src/app/components/MediaModal.tsx
import * as Dialog from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import { useMedia } from '../context/MediaContext';
import { motion, AnimatePresence } from 'motion/react';

export function MediaModal() {
    const { isOpen, closeMedia, currentMedia } = useMedia();

    return (
        <Dialog.Root open={isOpen} onOpenChange={(open) => !open && closeMedia()}>
            <AnimatePresence>
                {isOpen && (
                    <Dialog.Portal forceMount>
                        <Dialog.Overlay asChild>
                            <motion.div
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                className="fixed inset-0 bg-black/90 backdrop-blur-md z-[100]"
                                onClick={closeMedia}
                            />
                        </Dialog.Overlay>
                        <Dialog.Content asChild>
                            <motion.div
                                initial={{ opacity: 0, scale: 0.95 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.95 }}
                                className="fixed inset-0 z-[101] flex flex-col items-center justify-center p-2 md:p-8 pointer-events-none"
                            >
                                <div className="relative w-full h-full flex items-center justify-center pointer-events-none">
                                    {/* Close Button - more visible and fixed-like position */}
                                    <div className="absolute top-0 right-0 p-4 z-[102] pointer-events-auto">
                                        <Dialog.Close className="text-white/70 hover:text-white transition-all p-4 md:p-3 rounded-full bg-white/10 hover:bg-white/20 backdrop-blur-xl border border-white/20 shadow-lg">
                                            <X size={32} className="md:w-7 md:h-7 w-8 h-8" />
                                            <span className="sr-only">Chiudi</span>
                                        </Dialog.Close>
                                    </div>

                                    {/* Media Container */}
                                    <div className="w-full h-full flex items-center justify-center p-4">
                                        <div className="relative max-w-full max-h-full flex items-center justify-center pointer-events-auto shadow-2xl rounded-xl overflow-hidden">
                                            {currentMedia?.isVideo ? (
                                                <video
                                                    src={currentMedia.src}
                                                    controls
                                                    autoPlay
                                                    className="max-w-full max-h-[85vh] md:max-h-[90vh] object-contain"
                                                />
                                            ) : (
                                                <img
                                                    src={currentMedia?.src}
                                                    alt="Full screen media"
                                                    className="max-w-full max-h-[85vh] md:max-h-[90vh] object-contain"
                                                />
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </motion.div>
                        </Dialog.Content>
                    </Dialog.Portal>
                )}
            </AnimatePresence>
        </Dialog.Root>
    );
}
