// src/app/components/projects/projects.component.ts
import { Component, OnInit, OnDestroy, ElementRef, ViewChildren, QueryList } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subject, combineLatest, takeUntil } from 'rxjs';
import { SlickCarouselModule } from 'ngx-slick-carousel';
import { trigger, state, style, transition, animate } from '@angular/animations';
import { ApiService } from '../../services/api.service';
import { LanguageService } from '../../services/language.service';
import { MediaService } from '../../services/media.service';
import { MediaRendererComponent } from '../media-renderer/media-renderer.component';
import { Project, FixedTexts } from '../../models/api.models';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, MediaRendererComponent, SlickCarouselModule],
  template: `
    <section id="projects" class="flex flex-col justify-center px-4 py-8">
      <div class="max-w-4xl mx-auto w-full">
        @if (fixedTexts) {
          <div class="mb-12 text-center">
            <h2 class="text-white mb-4 text-4xl font-bold">{{ fixedTexts.projects.title }}</h2>
            <p class="text-white/70">
              {{ fixedTexts.projects.subtitle }}
            </p>
          </div>
        }

        <div class="space-y-4">
          @for (project of projects; track project.id) {
            <div 
              class="bg-white/5 backdrop-blur-sm rounded-lg border border-white/10 overflow-hidden"
              #projectElement
            >
              <button
                (click)="toggleProject(project.id)"
                class="w-full px-6 py-4 flex items-center justify-between hover:bg-white/5 transition-colors text-left"
              >
                <div class="flex-1">
                  <h3 class="text-white mb-1 text-xl font-medium">{{ project.name }}</h3>
                  <p class="text-white/60 text-sm">{{ project.description }}</p>
                </div>
                <div 
                  class="text-white/60 ml-4 transition-transform duration-300"
                  [class.rotate-180]="expandedProject === project.id"
                >
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M6 9l6 6 6-6"/>
                  </svg>
                </div>
              </button>

              @if (expandedProject === project.id) {
                <div 
                  [@expandCollapse]
                  class="overflow-hidden"
                >
                  <div class="px-6 pb-4 border-t border-white/10">
                    <div class="pt-4">
                      <!-- Image Carousel -->
                      @if (project.images && project.images.length > 0) {
                        <div class="mb-4 project-slider md:px-10 px-2">
                          <ngx-slick-carousel 
                            [config]="slideConfig" 
                            class="carousel"
                          >
                            @for (image of project.images; track $index) {
                              <div ngxSlickItem class="px-1">
                                <div class="relative aspect-video rounded-lg overflow-hidden">
                                  <app-media-renderer
                                    [url]="image"
                                    [type]="'image'"
                                    (mediaClick)="openMedia($event)"
                                  />
                                </div>
                              </div>
                            }
                          </ngx-slick-carousel>
                        </div>
                      }

                      <!-- Tech Stack -->
                      <div class="flex flex-wrap gap-2 mb-4">
                        @for (tech of project.tech; track tech) {
                          <span class="px-3 py-1 bg-white/10 text-white/80 rounded-full text-sm">
                            {{ tech }}
                          </span>
                        }
                      </div>

                      <!-- Challenges -->
                      @if (project.challenges && project.challenges.length > 0) {
                        <div class="mb-6 space-y-2">
                          <h4 class="text-white/80 font-medium mb-3">Sfide e Soluzioni</h4>
                          @for (challenge of project.challenges; track $index) {
                            <div class="bg-white/5 rounded-lg border border-white/10 overflow-hidden">
                              <details class="group">
                                <summary class="px-4 py-3 flex items-center justify-between cursor-pointer list-none hover:bg-white/5 transition-colors">
                                  <span class="text-white/90 text-sm font-medium">{{ challenge.problem }}</span>
                                  <span class="text-white/60 group-open:rotate-180 transition-transform">
                                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                      <path d="M6 9l6 6 6-6"/>
                                    </svg>
                                  </span>
                                </summary>
                                <div class="px-4 py-3 border-t border-white/10 bg-white/5 text-white/70 text-sm">
                                  <p><span class="text-green-400 font-medium">Soluzione:</span> {{ challenge.solution }}</p>
                                </div>
                              </details>
                            </div>
                          }
                        </div>
                      }

                      <!-- Links -->
                      <div class="flex gap-3 mb-4">
                        @if (project.github) {
                          <a
                            [href]="project.github"
                            class="flex items-center gap-2 text-white/70 hover:text-white transition-colors text-sm"
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                              <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/>
                            </svg>
                            <span>GitHub</span>
                          </a>
                        }
                        @if (project.demo) {
                          <a
                            [href]="project.demo"
                            class="flex items-center gap-2 text-white/70 hover:text-white transition-colors text-sm"
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>
                              <polyline points="15 3 21 3 21 9"/>
                              <line x1="10" y1="14" x2="21" y2="3"/>
                            </svg>
                            <span>Demo</span>
                          </a>
                        }
                      </div>

                      <!-- SubProjects -->
                      @if (project.subProjects && project.subProjects.length > 0) {
                        <div class="mt-4 space-y-2">
                          <p class="text-white/60 text-sm mb-2">Sotto-progetti:</p>
                          @for (subProject of project.subProjects; track subProject.id) {
                            <div 
                              class="bg-white/5 rounded-lg border border-white/10 overflow-hidden"
                              #subProjectElement
                            >
                              <button
                                (click)="toggleSubProject(subProject.id)"
                                class="w-full px-4 py-3 flex items-center justify-between hover:bg-white/5 transition-colors text-left"
                              >
                                <span class="text-white/80 text-sm">{{ subProject.name }}</span>
                                <div 
                                  class="text-white/60 transition-transform duration-300"
                                  [class.rotate-180]="expandedSubProject === subProject.id"
                                >
                                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path d="M6 9l6 6 6-6"/>
                                  </svg>
                                </div>
                              </button>

                              @if (expandedSubProject === subProject.id) {
                                <div 
                                  [@expandCollapse]
                                  class="overflow-hidden"
                                >
                                  <div class="px-4 pb-3 border-t border-white/10">
                                    <!-- SubProject Images -->
                                    @if (subProject.images && subProject.images.length > 0) {
                                      <div class="mt-3 mb-3 subproject-slider md:px-10 px-2">
                                        <ngx-slick-carousel 
                                          [config]="slideConfig" 
                                          class="carousel"
                                        >
                                          @for (image of subProject.images; track $index) {
                                            <div ngxSlickItem class="px-1">
                                              <div class="relative aspect-video rounded-lg overflow-hidden">
                                                <app-media-renderer
                                                  [url]="image"
                                                  [type]="'image'"
                                                  (mediaClick)="openMedia($event)"
                                                />
                                              </div>
                                            </div>
                                          }
                                        </ngx-slick-carousel>
                                      </div>
                                    }

                                    <!-- SubProject Details... (Simplified for brevity, matches structure) -->
                                    <p class="text-white/60 text-sm mb-3">
                                      {{ subProject.description }}
                                    </p>
                                    
                                     @if (subProject.challenges && subProject.challenges.length > 0) {
                                          <div class="mb-4 space-y-2">
                                            <p class="text-white/60 text-xs font-medium">Sfide:</p>
                                            @for (challenge of subProject.challenges; track $index) {
                                              <div class="bg-white/5 rounded border border-white/5 overflow-hidden">
                                                <details class="group">
                                                  <summary class="px-3 py-2 flex items-center justify-between cursor-pointer list-none hover:bg-white/5">
                                                    <span class="text-white/80 text-xs">{{ challenge.problem }}</span>
                                                      <span class="text-white/40 group-open:rotate-180 transition-transform">
                                                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                                          <path d="M6 9l6 6 6-6"/>
                                                        </svg>
                                                      </span>
                                                  </summary>
                                                  <div class="px-3 py-2 border-t border-white/5 bg-black/20 text-white/60 text-xs">
                                                    <span class="text-green-400/80">Soluzione: </span> {{ challenge.solution }}
                                                  </div>
                                                </details>
                                              </div>
                                            }
                                          </div>
                                        }

                                    @if (subProject.tech && subProject.tech.length > 0) {
                                      <div class="flex flex-wrap gap-2 mb-2">
                                        @for (tech of subProject.tech; track tech) {
                                          <span class="px-2 py-1 bg-white/10 text-white/70 rounded-full text-xs">
                                            {{ tech }}
                                          </span>
                                        }
                                      </div>
                                    }
                                  </div>
                                </div>
                              }
                            </div>
                          }
                        </div>
                      }
                    </div>
                  </div>
                </div>
              }
            </div>
          }
        </div>
      </div>
    </section>
  `,
  animations: [
    trigger('expandCollapse', [
      transition(':enter', [
        style({ height: '0', opacity: 0 }),
        animate('300ms ease-out', style({ height: '*', opacity: 1 }))
      ]),
      transition(':leave', [
        animate('300ms ease-in', style({ height: '0', opacity: 0 }))
      ])
    ])
  ]
})
export class ProjectsComponent implements OnInit, OnDestroy {
  fixedTexts: FixedTexts | null = null;
  projects: Project[] = [];
  expandedProject: string | null = null;
  expandedSubProject: string | null = null;
  private destroy$ = new Subject<void>();

  @ViewChildren('projectElement') projectElements!: QueryList<ElementRef>;
  @ViewChildren('subProjectElement') subProjectElements!: QueryList<ElementRef>;

  slideConfig = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: false,
    arrows: true
  };

  constructor(
    private apiService: ApiService,
    private languageService: LanguageService,
    private mediaService: MediaService
  ) { }

  ngOnInit(): void {
    combineLatest([
      this.languageService.currentLanguage$,
      this.languageService.fixedTexts$
    ])
      .pipe(takeUntil(this.destroy$))
      .subscribe(([lang, texts]) => {
        this.fixedTexts = texts;
        if (lang) {
          this.loadProjects(lang);
        }
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private loadProjects(lang: string): void {
    this.apiService.getProjects(lang)
      .pipe(takeUntil(this.destroy$))
      .subscribe(projects => this.projects = projects);
  }

  toggleProject(id: string): void {
    this.expandedProject = this.expandedProject === id ? null : id;
    this.expandedSubProject = null;

    // Scroll logic (simple timeout for DOM update)
    if (this.expandedProject) {
      setTimeout(() => {
        const element = this.projectElements.find((el, index) => this.projects[index].id === id);
        element?.nativeElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 300);
    }
  }

  toggleSubProject(id: string): void {
    this.expandedSubProject = this.expandedSubProject === id ? null : id;
    if (this.expandedSubProject) {
      setTimeout(() => {
        // Logic to find subproject element is slightly complex without direct map, 
        // but scrolling to nearest might be implicit or we can refine later.
        // For now, simple toggle is sufficient.
      }, 300);
    }
  }

  openMedia(event: { url: string, type: 'image' | 'video' }): void {
    this.mediaService.openMedia(event.url, event.type);
  }
}

// src/app/components/Projects.tsx
import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, Github, ExternalLink } from 'lucide-react';
import Slider from 'react-slick';
import { ImageWithFallback } from './figma/ImageWithFallback';



import { getProjects, Project } from '../../api';
import { useLanguage } from '../context/LanguageContext';

export function Projects() {
  const [expandedProject, setExpandedProject] = useState<string | null>(null);
  const [expandedSubProject, setExpandedSubProject] = useState<string | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);

  const projectRefs = useRef<{ [key: string]: HTMLDivElement | null }>({});
  const subProjectRefs = useRef<{ [key: string]: HTMLDivElement | null }>({});

  const { language, fixedTexts } = useLanguage();
  const t = fixedTexts?.projects;

  useEffect(() => {
    if (expandedProject && projectRefs.current[expandedProject]) {
      setTimeout(() => {
        projectRefs.current[expandedProject]?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 400);
    }
  }, [expandedProject]);

  useEffect(() => {
    if (expandedSubProject && subProjectRefs.current[expandedSubProject]) {
      setTimeout(() => {
        subProjectRefs.current[expandedSubProject]?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
      }, 400);
    }
  }, [expandedSubProject]);

  useEffect(() => {
    setLoading(true);
    getProjects(language)
      .then((data) => {
        setProjects(data);
        setLoading(false);
      })
      .catch((error) => {
        console.error('Error fetching projects:', error);
        setLoading(false);
      });
  }, [language]);

  if (loading) {
    return <div className="text-white text-center py-20">Loading projects...</div>;
  }

  const toggleProject = (id: string) => {
    setExpandedProject(expandedProject === id ? null : id);
    setExpandedSubProject(null);
  };

  const toggleSubProject = (id: string) => {
    setExpandedSubProject(expandedSubProject === id ? null : id);
  };

  const sliderSettings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: false,
    arrows: true,
  };

  return (
    <section id="projects" className="flex flex-col justify-center px-4 py-8">
      <div className="max-w-4xl mx-auto w-full">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <h2 className="text-white mb-4 text-center">{t?.title || 'Progetti'}</h2>
          <p className="text-white/70 text-center mb-12">
            {t?.subtitle || 'Alcuni dei progetti su cui ho lavorato'}
          </p>
        </motion.div>

        <div className="space-y-4">
          {projects.map((project, index) => (
            <motion.div
              key={project.id}
              ref={(el: HTMLDivElement | null) => {
                if (el) projectRefs.current[project.id] = el;
              }}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              style={{ scrollMarginTop: '100px' }}
              className="bg-white/5 backdrop-blur-sm rounded-lg border border-white/10 overflow-hidden"
            >
              <button
                onClick={() => toggleProject(project.id)}
                className="w-full px-6 py-4 flex items-center justify-between hover:bg-white/5 transition-colors"
              >
                <div className="text-left flex-1">
                  <h3 className="text-white mb-1">{project.name}</h3>
                  <p className="text-white/60 text-sm">{project.description}</p>
                </div>
                <motion.div
                  animate={{ rotate: expandedProject === project.id ? 180 : 0 }}
                  transition={{ duration: 0.3 }}
                  className="text-white/60 ml-4"
                >
                  <ChevronDown size={20} />
                </motion.div>
              </button>

              <AnimatePresence>
                {expandedProject === project.id && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className="overflow-hidden"
                  >
                    <div className="px-6 pb-4 border-t border-white/10">
                      <div className="pt-4">
                        {/* Image Carousel */}
                        {project.images && project.images.length > 0 && (
                          <div className="mb-4 project-slider px-10">
                            <Slider {...sliderSettings}>
                              {project.images.map((image, idx) => (
                                <div key={idx} className="px-1">
                                  <div className="relative aspect-video rounded-lg overflow-hidden">
                                    <ImageWithFallback
                                      src={image}
                                      alt={`${project.name} - Image ${idx + 1}`}
                                      className="w-full h-full object-cover"
                                    />
                                  </div>
                                </div>
                              ))}
                            </Slider>
                          </div>
                        )}

                        <div className="flex flex-wrap gap-2 mb-4">
                          {project.tech.map((tech) => (
                            <span
                              key={tech}
                              className="px-3 py-1 bg-white/10 text-white/80 rounded-full text-sm"
                            >
                              {tech}
                            </span>
                          ))}
                        </div>

                        {/* Challenges and Solutions */}
                        {project.challenges && project.challenges.length > 0 && (
                          <div className="mb-6 space-y-2">
                            <h4 className="text-white/80 font-medium mb-3">Sfide e Soluzioni</h4>
                            {project.challenges.map((challenge, cIndex) => (
                              <div
                                key={cIndex}
                                className="bg-white/5 rounded-lg border border-white/10 overflow-hidden"
                              >
                                <button
                                  onClick={() => {
                                    // Helper function or inline state management for generic accordion needed if we want independent toggle
                                    // For simplicity using a local map or just use details/summary or Radix.
                                    // Let's implement a simple inline toggle for this specific map if possible, 
                                    // BUT, implementing state for dynamic list inside a mapped component (Project) is tricky without extracting a component.
                                    // Let's Extract 'ChallengeItem' component inline or use details element for native behavior 
                                    // OR better: Create a ChallengeAccordion component outside.
                                    // Since I can't create new file easily without planning, I will make a simple toggle using state is hard here.
                                    // User asked for "Drop Down", so native <details> is perfect and simple.
                                  }}
                                  className="w-full text-left"
                                >
                                  <details className="group">
                                    <summary className="px-4 py-3 flex items-center justify-between cursor-pointer list-none hover:bg-white/5 transition-colors">
                                      <span className="text-white/90 text-sm font-medium">{challenge.problem}</span>
                                      <span className="text-white/60 group-open:rotate-180 transition-transform">
                                        <ChevronDown size={16} />
                                      </span>
                                    </summary>
                                    <div className="px-4 py-3 border-t border-white/10 bg-white/5 text-white/70 text-sm">
                                      <p><span className="text-green-400 font-medium">Soluzione:</span> {challenge.solution}</p>
                                    </div>
                                  </details>
                                </button>
                              </div>
                            ))}
                          </div>
                        )}

                        <div className="flex gap-3 mb-4">
                          {project.github && (
                            <a
                              href={project.github}
                              className="flex items-center gap-2 text-white/70 hover:text-white transition-colors text-sm"
                              target="_blank"
                              rel="noopener noreferrer"
                            >
                              <Github size={16} />
                              <span>GitHub</span>
                            </a>
                          )}
                          {project.demo && (
                            <a
                              href={project.demo}
                              className="flex items-center gap-2 text-white/70 hover:text-white transition-colors text-sm"
                              target="_blank"
                              rel="noopener noreferrer"
                            >
                              <ExternalLink size={16} />
                              <span>Demo</span>
                            </a>
                          )}
                        </div>

                        {project.subProjects && project.subProjects.length > 0 && (
                          <div className="mt-4 space-y-2">
                            <p className="text-white/60 text-sm mb-2">Sotto-progetti:</p>
                            {project.subProjects.map((subProject) => (
                              <div
                                key={subProject.id}
                                ref={(el: HTMLDivElement | null) => {
                                  if (el) subProjectRefs.current[subProject.id] = el;
                                }}
                                style={{ scrollMarginTop: '120px' }}
                                className="bg-white/5 rounded-lg border border-white/10 overflow-hidden"
                              >
                                <button
                                  onClick={() => toggleSubProject(subProject.id)}
                                  className="w-full px-4 py-3 flex items-center justify-between hover:bg-white/5 transition-colors"
                                >
                                  <span className="text-white/80 text-sm">{subProject.name}</span>
                                  <motion.div
                                    animate={{ rotate: expandedSubProject === subProject.id ? 180 : 0 }}
                                    transition={{ duration: 0.3 }}
                                    className="text-white/60"
                                  >
                                    <ChevronDown size={16} />
                                  </motion.div>
                                </button>

                                <AnimatePresence>
                                  {expandedSubProject === subProject.id && (
                                    <motion.div
                                      initial={{ height: 0, opacity: 0 }}
                                      animate={{ height: 'auto', opacity: 1 }}
                                      exit={{ height: 0, opacity: 0 }}
                                      transition={{ duration: 0.3 }}
                                      className="overflow-hidden"
                                    >
                                      <div className="px-4 pb-3 border-t border-white/10">
                                        {/* SubProject Image Carousel */}
                                        {subProject.images && subProject.images.length > 0 && (
                                          <div className="mt-3 mb-3 subproject-slider px-10">
                                            <Slider {...sliderSettings}>
                                              {subProject.images.map((image, idx) => (
                                                <div key={idx} className="px-1">
                                                  <div className="relative aspect-video rounded-lg overflow-hidden">
                                                    <ImageWithFallback
                                                      src={image}
                                                      alt={`${subProject.name} - Image ${idx + 1}`}
                                                      className="w-full h-full object-cover"
                                                    />
                                                  </div>
                                                </div>
                                              ))}
                                            </Slider>
                                          </div>
                                        )}

                                        {/* SubProject Challenges */}
                                        {subProject.challenges && subProject.challenges.length > 0 && (
                                          <div className="mb-4 space-y-2">
                                            <p className="text-white/60 text-xs font-medium">Sfide:</p>
                                            {subProject.challenges.map((challenge, scIndex) => (
                                              <div key={scIndex} className="bg-white/5 rounded border border-white/5 overflow-hidden">
                                                <details className="group">
                                                  <summary className="px-3 py-2 flex items-center justify-between cursor-pointer list-none hover:bg-white/5">
                                                    <span className="text-white/80 text-xs">{challenge.problem}</span>
                                                    <ChevronDown size={12} className="text-white/40 group-open:rotate-180 transition-transform" />
                                                  </summary>
                                                  <div className="px-3 py-2 border-t border-white/5 bg-black/20 text-white/60 text-xs">
                                                    <span className="text-green-400/80">Soluzione: </span> {challenge.solution}
                                                  </div>
                                                </details>
                                              </div>
                                            ))}
                                          </div>
                                        )}

                                        <p className="text-white/60 text-sm mb-3">
                                          {subProject.description}
                                        </p>
                                        <div className="flex flex-wrap gap-2 mb-2">
                                          {subProject.tech.map((tech) => (
                                            <span
                                              key={tech}
                                              className="px-2 py-1 bg-white/10 text-white/70 rounded-full text-xs"
                                            >
                                              {tech}
                                            </span>
                                          ))}
                                        </div>
                                        {subProject.link && (
                                          <a
                                            href={subProject.link}
                                            className="flex items-center gap-1 text-white/70 hover:text-white transition-colors text-xs"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                          >
                                            <ExternalLink size={12} />
                                            <span>Vedi dettagli</span>
                                          </a>
                                        )}
                                      </div>
                                    </motion.div>
                                  )}
                                </AnimatePresence>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div >
    </section >
  );
}
